# Generated by Django 5.2.5 on 2025-09-08 08:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nome"),
                ),
                (
                    "formula",
                    models.CharField(max_length=50, verbose_name="Fórmula Química"),
                ),
                (
                    "molecular_weight",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Peso Molecular (g/mol)",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Espécie Química",
                "verbose_name_plural": "Espécies Químicas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReactionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Nome da Reação"),
                ),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "reaction_order",
                    models.IntegerField(
                        choices=[(0, "Ordem 0"), (1, "Ordem 1"), (2, "Ordem 2")],
                        default=1,
                        verbose_name="Ordem da Reação",
                    ),
                ),
                (
                    "rate_constant",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0001)],
                        verbose_name="Constante Cinética (k)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="reactions_as_product",
                        to="chemical_simulator.species",
                        verbose_name="Produtos",
                    ),
                ),
                (
                    "reactants",
                    models.ManyToManyField(
                        related_name="reactions_as_reactant",
                        to="chemical_simulator.species",
                        verbose_name="Reagentes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de Reação",
                "verbose_name_plural": "Templates de Reação",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SimulationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome da Simulação"),
                ),
                (
                    "initial_concentrations",
                    models.JSONField(
                        help_text="JSON com concentrações iniciais das espécies",
                        verbose_name="Concentrações Iniciais",
                    ),
                ),
                (
                    "time_span",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Tempo de Simulação (s)",
                    ),
                ),
                (
                    "time_points",
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name="Pontos Temporais",
                    ),
                ),
                (
                    "results",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Resultados da Simulação"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("running", "Em Execução"),
                            ("completed", "Concluída"),
                            ("failed", "Falhada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensagem de Erro"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chemical_simulator.reactiontemplate",
                        verbose_name="Template de Reação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulação",
                "verbose_name_plural": "Simulações",
                "ordering": ["-created_at"],
            },
        ),
    ]
