# Generated by Django 5.2.5 on 2025-09-08 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chemical_simulator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="cas_number",
            field=models.CharField(
                blank=True,
                help_text="Número de registro CAS (ex: 7732-18-5)",
                max_length=15,
                verbose_name="Número CAS",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="color",
            field=models.CharField(
                choices=[
                    ("incolor", "Incolor"),
                    ("white", "Branco"),
                    ("yellow", "Amarelo"),
                    ("red", "Vermelho"),
                    ("blue", "Azul"),
                    ("green", "Verde"),
                    ("brown", "Castanho"),
                    ("black", "Preto"),
                    ("purple", "Roxo"),
                    ("orange", "Laranja"),
                ],
                default="incolor",
                max_length=10,
                verbose_name="Cor",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="default_concentration",
            field=models.FloatField(
                default=1,
                help_text="Concentração típica para simulações",
                validators=[
                    django.core.validators.MinValueValidator(0.0001),
                    django.core.validators.MaxValueValidator(100.0),
                ],
                verbose_name="Concentração Padrão Sugerida (mol·L⁻¹)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="species",
            name="density",
            field=models.FloatField(
                blank=True,
                help_text="Densidade a 25°C",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.001)],
                verbose_name="Densidade (g/cm³)",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="physical_state",
            field=models.CharField(
                choices=[
                    ("solid", "Sólido"),
                    ("liquid", "Líquido"),
                    ("gas", "Gasoso"),
                    ("aqueous", "Aquoso"),
                ],
                default="aqueous",
                max_length=10,
                verbose_name="Estado Físico (25°C)",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="simulation_role",
            field=models.CharField(
                choices=[
                    ("reactant", "Reagente"),
                    ("product", "Produto"),
                    ("catalyst", "Catalisador"),
                    ("solvent", "Solvente"),
                    ("intermediate", "Intermediário"),
                ],
                default="reactant",
                max_length=12,
                verbose_name="Papel na Simulação",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="transparency",
            field=models.CharField(
                choices=[
                    ("transparent", "Transparente"),
                    ("translucent", "Translúcido"),
                    ("opaque", "Opaco"),
                ],
                default="transparent",
                max_length=15,
                verbose_name="Transparência",
            ),
        ),
        migrations.AlterField(
            model_name="reactiontemplate",
            name="reaction_order",
            field=models.IntegerField(
                choices=[(1, "1ª Ordem"), (2, "2ª Ordem"), (3, "3ª Ordem")],
                default=1,
                verbose_name="Ordem da Reação",
            ),
        ),
    ]
