# Generated by Django 5.2.5 on 2025-09-23 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chemical_simulator", "0002_species_cas_number_species_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reactiontemplate",
            name="intermediates",
            field=models.ManyToManyField(
                blank=True,
                related_name="reactions_as_intermediate",
                to="chemical_simulator.species",
                verbose_name="Intermediários",
            ),
        ),
        migrations.AlterField(
            model_name="reactiontemplate",
            name="reaction_order",
            field=models.IntegerField(
                choices=[(1, "0ª Ordem"), (2, "1ª Ordem"), (3, "2ª Ordem")],
                default=1,
                verbose_name="Ordem da Reação",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="color",
            field=models.CharField(
                choices=[
                    ("incolor", "Incolor"),
                    ("white", "Branco"),
                    ("yellow", "Amarelo"),
                    ("red", "Vermelho"),
                    ("blue", "Azul"),
                    ("green", "Verde"),
                    ("brown", "Castanho"),
                    ("black", "Preto"),
                    ("purple", "Roxo"),
                    ("orange", "Laranja"),
                    ("gray", "Cinza"),
                ],
                default="incolor",
                max_length=10,
                verbose_name="Cor",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="density",
            field=models.FloatField(
                blank=True,
                help_text="Densidade a 25°C",
                null=True,
                validators=[django.core.validators.MinValueValidator(1e-05)],
                verbose_name="Densidade (g/cm³)",
            ),
        ),
    ]
